begin
  int f() is
    return 0 / 0
  end
  try
    call f();
    println "Should not have reached this"
  catch
    println "Exception caught"
  end